services:
  - type: web
    name: crop-disease-detection-ml
    runtime: python
    repo: https://github.com/Rahul565880/Crop-Disease-Detection
    branch: master
    plan: free
    buildCommand: pip install -r ml-service/requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    rootDir: ml-service
    healthCheckPath: /health
